// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import HitReducer from "../hit_reducer";
import ReteeReducer from "../retee_reducer";
import SpawnReducer from "../spawn_reducer";

export type HitParams = __Infer<typeof HitReducer>;
export type ReteeParams = __Infer<typeof ReteeReducer>;
export type SpawnParams = __Infer<typeof SpawnReducer>;

