// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  ballState: __t.u8().name("ball_state"),
  shotAge: __t.f64().name("shot_age"),
  tHalf: __t.f64().name("t_half"),
  phase: __t.u8(),
  hole: __t.u8(),
  strokes: __t.u32(),
  totalStrokes: __t.u32().name("total_strokes"),
  courseChoice: __t.u8().name("course_choice"),
  connected: __t.bool(),
  offlineSinceTick: __t.u64().name("offline_since_tick"),
});
