// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Conn = __t.object("Conn", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
});
export type Conn = __Infer<typeof Conn>;

export const Meta = __t.object("Meta", {
  id: __t.u32(),
  tick: __t.u64(),
});
export type Meta = __Infer<typeof Meta>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  state: __t.u8(),
  strokes: __t.u32(),
  shotAge: __t.f64(),
  tHalf: __t.f64(),
  connected: __t.bool(),
  offlineSinceTick: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

